openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-azure-redis
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          required:
          - resource_group
          properties:
            domain_suffix:
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 1
            publicly_accessible:
              default: false
              title: Publicly Accessible
              type: boolean
              x-walrus-ui:
                order: 4
            resource_group:
              title: Resource Group
              type: string
              x-walrus-ui:
                order: 1
            subnet:
              title: Subnet
              type: string
              x-walrus-ui:
                order: 3
            virtual_network:
              title: Virtual Network
              type: string
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version of the Redis Server to use. Possible values are 6.0, and 4.0.
          default: "6.0"
          enum:
          - "6.0"
          - "4.0"
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
            Please note that the resources class is only available for the Basic, Standard, and Premium pricing tiers.
            See https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview#pricing for more information.
            Examples:
            ```
            resources:
              class: string, optional            # sku
            ```
          default:
            class: Basic
          enum:
          - Basic
          - Standard
          - Premium
          properties:
            class:
              default: Basic
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        storage:
          title: Storage
          type: object
          description: |
            The storage size of the Redis cache. Valid values for a SKU family of C (Basic/Standard) are 0, 1, 2, 3, 4, 5, 6, and for P (Premium) family are 1, 2, 3, 4, 5
          default:
            size: 1
          properties:
            size:
              default: 1
              title: Size
              type: number
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
